FORMAT: 1A
HOST: http://docs.schools1.apiary.io/

# schools

Schools é uma api para manter informações sobre escolas e seus registros administrativos.

## Auth Collection [/auth]

### Request access [POST]

Registra a solicitação de acesso do usuário.
O usuário é registrado como papel (role) de convidado (guest),
até que algum usuário que tenha permissão para liberação de usuários
confirme a solicitação de acesso e atribua um novo papel (role ).

+ Request
    + Headers
    
                Authorization: Bearer <token_id>

+ Response 200 (application/json)

        {
            "id": 100,
            "user_id": 10,
            "status": 0,
            "created_at": "2016-08-15 20:26:39",
            "updated_at": "2016-08-15 21:26:39"
            
        }

### Create a New Question [GET]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "question": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }