version: '2'
services:
  web:
    image: keviocastro/laravel:5
    environment:
      APP_ENV: prodution
      APP_DEBUG: false
    depends_on:
      - db
    volumes:
      - ".:/var/app/"
      - "~/.bash_history:/root/.bash_history"
    ports:
      - "80:80"
    links:
      - "db"
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: schools
    volumes:
      - "./docker/mysql:/etc/mysql/conf.d"