version: '2'
services:
  web:
    build: .
    environment:
      XDEBUG_CONFIG: remote_host=192.168.0.19
    depends_on:
      - db
    volumes:
      - ".:/var/app/"
      - "~/.bash_history:/root/.bash_history"
    ports:
      - "80:80"
    links:
      - "db"
      - "redis"
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: schools
    volumes:
      - "./docker/mysql:/etc/mysql/conf.d"
  redis:
    image: redis:3
