# Group Aulas

## Coleção de aulas [/lessons]

`Lessons` são as aulas programadas para as turmas de uma escola.

### Listar aulas [GET]

<!-- include(LinkParametrosPadroesListagem.md) -->


+ Parameters
    + _q (string, optional) - Pesquisa por palavra-chave, a correspondência e incluida conjunto de resultados.
    + _sort (string, optional) - Ordena a coluna desejada, de forma acendente ou descendente.
    + _with (string, optional) - Obtem informações do recurso relacionado.
        + Members
            + schoolClass
            + schoolClass.grade
            + schoolClass.shift
            + subject
            + lessonPlan

+ Request  (application/json)
    + Headers

            authorization: <!-- include(Token.md) -->

+ Response 200 (application/json)

    + Attributes
        + Include Paginator
        + data (array)
            + (Lesson)

### Criar aula [POST]

+ Request  (application/json)
    + Headers

            authorization: <!-- include(Token.md) -->

    + Attributes (LessonFillable)

+ Response 201 (application/json)

    + Attributes
        + lesson (Lesson)


## Aula [/lessons/{lesson_id}]

### Detalhes da aula [GET]

+ Parameters
    + lesson_id: 1 (number) - ID of the lesson
    + _with (string, optional) Nome da relação a ser incluida na resposta.
        + Members
            + attendanceRecords
            + schoolClass
            + schoolClass.grade
            + schoolClass.students
            + schoolClass.shift
            + schoolClass.students.responsibles
            + schoolClass.students.attendanceRecords
            + schoolClass.students.person
            + lessonPlan

    + attach (string, optional)

        Anexa mais informações da aula na responsta.
        students.last_occurences são as ultimas 2 ocorrencias do aluno.
        students.attendanceRecord é o registro de chamada da aula para o aluno.
        students.absenceSummary é um resumo de faltas do aluno, durante o ano.

        + Members
            + students
            + students.attendanceRecord
            + students.last_occurences
            + students.absenceSummary

+ Request  (application/json)
    + Headers

            authorization: <!-- include(Token.md) -->

+ Response 200 (application/json)

    + Attributes
        + lesson
            + Include (Lesson)
            + students (array)
                + (object)
                    + Include (Student)
                    + attendance_record (AttendanceRecord)
                    + last_occurences (array[Occurence])
                    + absence_summary (object)
                        + percentage_absences_reprove: 25 - Percentual máximo de faltas as aulas para não ser           reprovado
                        + total_lessons_year: 200 - total de aulas programadas no ano da mesma disciplina
                        + total_absences_year: 22 - total de faltas que o aluno tem no ano da mesma disciplina

### Alterar aula [PUT]

+ Parameters
    + lesson_id: 1 (number) - ID of the lesson

+ Request  (application/json)
    + Headers

            authorization: <!-- include(Token.md) -->

    + Attributes (LessonFillable)

+ Response 200 (application/json)

    + Attributes
        + lesson (Lesson)


### Excluir aula [DELETE]

+ Parameters
    + lesson_id: 1 (number) - ID of the lesson

+ Request  (application/json)
    + Headers

            authorization: <!-- include(Token.md) -->

+ Response 204


## Aulas por dia [/lessons/per-day]

### Listar aulas por dia [GET]

<!-- include(LinkParametrosPadroesListagem.md) -->

+ Parameters
    + start (string, optional) Data inicial
        + Default: NOW()
    + end (string, optional) Data final
        + Default: NOW() + 15 days
    + _with (string, optional) Nome da relação a ser incluida da resposta.
        + Members
            + schoolClass
            + schoolClass.grade
            + schoolClass.shift
            + schoolClass.students
            + schoolClass.students.studentResponsible
            + schoolClass.students.attendanceRecords
            + subject

+ Request  (application/json)
    + Headers

            authorization: <!-- include(Token.md) -->

+ Response 200 (application/json)

    + Attributes
        + start: '2016-10-01' (string)
        + end: '2016-10-15' (string)
        + data (array)
            + (object)
                + day: `2016-10-01` (string)
                + lessons (array[Lesson])


## Coleção de planos de aula [/lesson-plans]

`Lesson plan` são planejamentos dos professores para como e quando vão aplicar conteúdos na sala de aula. 

### Listar planos de aula [GET]

+ Parameters
    + _q (string, optional) - Pesquisa por palavra-chave, a correspondência e incluida conjunto de resultados.
    + _sort (string, optional) - Ordena a coluna desejada, de forma acendente ou descendente.
    + _with (string, optional) - Obtem informações do recurso relacionado.
        + Members
            + LessonPlanModel

+ Request  (application/json)
    + Headers

            authorization: <!-- include(Token.md) -->

+ Response 200 (application/json)

    + Attributes
        + Include Paginator
        + data (array)
            + (LessonPlan)


### Criar plano de aula [POST]

+ Request  (application/json)
    + Headers

            authorization: <!-- include(Token.md) -->

    + Attributes (object)
        + Include LessonPlanFillable
        + lesson_ids (array) - `Array com ID das aulas a quais o plano de 
        aula é relacionado` 
            - Sample
                + 1 (number)

+ Response 201 (application/json)

    + Attributes
        + lesson_plan (object) - Dados do plano de aula criado
            + Include LessonPlan
            + lessons (array[Lesson]) - Aulas relacionadas ao plano de aula

## Plano de aula [/lesson-plans/{lesson_plan_id}]

### Detalhes do plano de aula [GET]

+ Parameters
    + lesson_plan_id: 1 (number) - ID of the lesson plan
    + _with (string, optional) Nome da relação a ser incluida na resposta.
        + Members
            + LessonPlanModel

+ Request  (application/json)
    + Headers

            authorization: <!-- include(Token.md) -->

+ Response 200 (application/json)

    + Attributes
        + Include (LessonPlan)

### Alterar plano de aula [PUT]

+ Parameters
    + lesson_plan_id: 1 (number) - ID of the lesson plan

+ Request  (application/json)
    + Headers

            authorization: <!-- include(Token.md) -->

    + Attributes (object)
        + Include LessonPlanFillable
        + lesson_ids (array) - `Array com ID das aulas a quais o plano de 
        aula será relacionado. 
        Somente os ids enviados nesse parametro estarão relacionados ao plano.
        Qualquer outra aula que não estiver nesse parametro será desassociada.` 
            - Sample
                + 1 (number)

+ Response 200 (application/json)

    + Attributes
        + lesson_plan (object) - Dados do plano de aula criado
            + Include LessonPlan
            + lessons (array[Lesson]) - Aulas relacionadas ao plano de aula


### Excluir plano de aula [DELETE]

+ Parameters
    + lesson_plan_id: 1 (number) - ID of the lesson plan

+ Request  (application/json)
    + Headers

            authorization: <!-- include(Token.md) -->

+ Response 204


## Coleção de modelos para planos de aula [/lesson-plan-models]

'Modelos de plano de aula' são definições de formatos que os professores devem seguir
ao criar seus planos de aula

<!-- include(LinkParametrosPadroesListagem.md) -->

### Listar modelos de plano de aula [GET]

+ Request  (application/json)
    + Headers

            authorization: <!-- include(Token.md) -->

+ Response 200 (application/json)

    + Attributes
        + Include Paginator
        + data (array)
            + (LessonPlanModel)

### Criar modelo de plano de aula [POST]

+ Request  (application/json)
    + Headers

            authorization: <!-- include(Token.md) -->

    + Attributes (LessonPlanModelFillable)

+ Response 201 (application/json)

    + Attributes
        + lesson_plan_Model (LessonPlanModel)

## Modelo de plano de aulas [/lesson-plan-models/{lesson_plan_model_id}]

### Detalhes do modelo de plano de aula [GET]

+ Parameters
    + lesson_plan_model_id: 1 (number) - ID of the model lesson plan

+ Request  (application/json)
    + Headers

            authorization: <!-- include(Token.md) -->

+ Response 200 (application/json)

    + Attributes
        + Include (LessonPlanModel)

### Alterar modelo de plano de aula [PUT]

+ Parameters
    + lesson_plan_model_id: 1 (number) - ID of the model lesson plan

+ Request  (application/json)
    + Headers

            authorization: <!-- include(Token.md) -->

    + Attributes (LessonPlanModelFillable)

+ Response 200 (application/json)

    + Attributes
        + lesson_plan_model (LessonPlanModel)

### Excluir modelo de plano de aula [DELETE]

+ Parameters
    + lesson_plan_model_id: 1 (number) - ID of the model lesson plan

+ Request  (application/json)
    + Headers

            authorization: <!-- include(Token.md) -->

+ Response 204