# Group Avaliações

## Coleção de avaliacoes [/assessments]

`Assessments` são as definições das avaliações que um professor precisar aplicar
aos seus alunos durante uma fase do ano.
Exemplo: No 1º Bimestre o professor precisa avaliar seus alunos com duas provas (N1 e N2),
e a nota do aluno no 1º Bimestre será composta pela conta (N1*0,4)+(N2*0,6)=NOTA_DO_BIMESTRE.

### Listar avaliações [GET]

<!-- include(LinkParametrosPadroesListagem.md) -->


+ Parameters
    + _q (string, optional) - Pesquisa por palavra-chave, a correspondência e incluida conjunto de resultados.
        + Members
            +name
    + _sort (string, optional) - Ordena a coluna desejada, de forma acendente ou descendente.
    + _with (string, optional) - Obtem informações do recurso relacionado.
        + Members
            + studentGrades
            + schoolCalendarPhase

+ Request  (application/json)
    + Headers

            authorization: <!-- include(Token.md) -->

+ Response 200 (application/json)

    + Attributes
        + Include Paginator
        + data (array)
            + (Assessment)



## Coleção de fichas avaliativas [/progress_sheets{?_q,_sort,_with}]

`progress_sheets` são fichas avaliativas do desempenho do aluno.

### Listar de fichas avaliativas [GET]

<!-- include(LinkParametrosPadroesListagem.md) -->

+ Parameters
    + _q (string, optional) - Pesquisa por palavra-chave, a correspondência e incluida conjunto de resultados.
        + Members
            +name
    + _sort (string, optional) - Ordena a coluna desejada, de forma acendente ou descendente.
    + _with (string, optional) - Obtem informações do recurso relacionado.
        + Members
            + progressSheet

+ Request  (application/json)
    + Headers

            authorization: <!-- include(Token.md) -->

+ Response 200 (application/json)

    + Attributes
        + Include Paginator
        + data (array)
            + (ProgressSheets)

### Criar ficha avaliativa [POST]

+ Request  (application/json)
    + Headers

            authorization: <!-- include(Token.md) -->

    + Attributes (ProgressSheetsFillable)

+ Response 201 (application/json)

    + Attributes
        + progressSheets (ProgressSheets)


## ficha avaliativa [/progress_sheets/{progress_sheet_id}]

### Detalhes da ficha avaliativa [GET]

+ Parameters
    + progress_sheet_id: 1 (number) - ID da ficha avaliativa

+ Request  (application/json)
    + Headers

            authorization: <!-- include(Token.md) -->

+ Response 200 (application/json)

    + Attributes
        + progressSheets (ProgressSheets)

### Alterar ficha avaliativa [PUT]

+ Parameters
    + progress_sheet_id: 1 (number) - ID da ficha avaliativa

+ Request  (application/json)
    + Headers

            authorization: <!-- include(Token.md) -->

    + Attributes (ProgressSheetsFillable)

+ Response 200 (application/json)

    + Attributes
        + progressSheets (ProgressSheets)


### Excluir ficha avaliativa [DELETE]

+ Parameters
    + progress_sheet_id: 1 (number) - ID da ficha avaliativa

+ Request  (application/json)
    + Headers

            authorization: <!-- include(Token.md) -->

+ Response 204



## Coleção de items da fichas avaliativas [/progress_sheet_items{?_q,_sort,_with}]

`progress_sheet_items` são items da fichas avaliativas do desempenho do aluno.

### Listar items da fichas avaliativas [GET]

<!-- include(LinkParametrosPadroesListagem.md) -->

+ Parameters
    + _q (string, optional) - Pesquisa por palavra-chave, a correspondência e incluida conjunto de resultados.
        + Members
            +name
    + _sort (string, optional) - Ordena a coluna desejada, de forma acendente ou descendente.
    + _with (string, optional) - Obtem informações do recurso relacionado.
        + Members
            + progressSheet

+ Request  (application/json)
    + Headers

            authorization: <!-- include(Token.md) -->

+ Response 200 (application/json)

    + Attributes
        + Include Paginator
        + data (array)
            + (ProgressSheetItems)

### Criar item da ficha avaliativa [POST]

+ Request  (application/json)
    + Headers

            authorization: <!-- include(Token.md) -->

    + Attributes (ProgressSheetItemsFillable)

+ Response 201 (application/json)

    + Attributes
        + progressSheetItems (ProgressSheetItems)


## Item da ficha avaliativa [/progress_sheet_items/{progress_sheet_item_id}]

### Detalhes do item da ficha avaliativa [GET]

+ Parameters
    + progress_sheet_item_id: 1 (number) - ID do item da ficha avaliativa

+ Request  (application/json)
    + Headers

            authorization: <!-- include(Token.md) -->

+ Response 200 (application/json)

    + Attributes
        + progressSheetItems (ProgressSheetItems)

### Alterar item da ficha avaliativa [PUT]

+ Parameters
    + progress_sheet_item_id: 1 (number) - ID do item da ficha avaliativa

+ Request  (application/json)
    + Headers

            authorization: <!-- include(Token.md) -->

    + Attributes (ProgressSheetItemsFillable)

+ Response 200 (application/json)

    + Attributes
        + progressSheetItems (ProgressSheetItems)


### Excluir item da ficha avaliativa [DELETE]

+ Parameters
    + progress_sheet_item_id: 1 (number) - ID do item da ficha avaliativa

+ Request  (application/json)
    + Headers

            authorization: <!-- include(Token.md) -->

+ Response 204
