# Group Calendários escolares

`Calendário escolar` (definido nesta API como SchoolCalendar) é considerado como a definição do ano letivo,
contendo fases fases avaliativas do ano (Ex.: bimestres), feriados, férias,
inicio e fim do ano.

## Coleção de calendarios escolares [/school-calendars]

### Listar calendarios escolares [GET]

<!-- include(LinkParametrosPadroesListagem.md) -->

+ Parameters
    + _q (string, optional) - Pesquisa por palavra-chave, a correspondência e incluida conjunto de resultados.
    + _sort (string, optional) - Ordena a coluna desejada, de forma acendente ou descendente.
    + _with (string, optional) - Obtem informações do recurso relacionado.
        + Members
            + schoolClasses - Turmas do ano letivo.
            + schoolCalendarPhase - Fases avaliativas do ano letivo. Recurso (SchoolCalendarPhase)

+ Request  (application/json)

    + Headers

            authorization: <!-- include(Token.md) -->

+ Response 200 (application/json)

    + Attributes
        + Include Paginator
        + data (array)
            + (SchoolCalendar)

### Criar calendário escolar [POST]

+ Request  (application/json)
    + Headers

            authorization: <!-- include(Token.md) -->

    + Attributes (SchoolCalendarFillable)

+ Response 201 (application/json)

    + Attributes
        + school_calendar (SchoolCalendar)

## Calendário escolar [/school-calendars/{school_calendar_id}]

### Detalhes do calendário escolar [GET]

+ Parameters
    + school_calendar_id: 1 (number) - ID of the school class
    + _with (string, optional) - Obtem informações do recurso relacionado.
        + Members
            + schoolClasses - Turmas do ano letivo.
            + schoolCalendarPhase - Fases avaliativas do ano letivo. Recurso (SchoolCalendarPhase)

+ Request  (application/json)
    + Headers

            authorization: <!-- include(Token.md) -->

+ Response 200 (application/json)

    + Attributes
        + school_calendar (SchoolCalendar)

### Alterar calendário [PUT]

+ Parameters
    + school_calendar_id: 1 (number) - ID of the school class

+ Request  (application/json)
    + Headers

            authorization: <!-- include(Token.md) -->

    + Attributes (SchoolCalendarFillable)

+ Response 200 (application/json)

    + Attributes
        + school_calendar (SchoolCalendar)

### Excluir calendário [DELETE]

+ Parameters
    + school_calendar_id: 1 (number) - ID of the School

+ Request  (application/json)

    + Headers

            authorization: <!-- include(Token.md) -->

+ Response 204

