# Group Configurações

## Colleção de configurações da conta [/account-configs]

Configurações da contado do usuário logado.

### Listar configurações [GET]

<!-- include(LinkParametrosPadroesListagem.md) -->


+ Request  (application/json)
    + Headers

            authorization: <!-- include(Token.md) -->

+ Response 200 (application/json)

    + Attributes
        + account_configs (array)
            + (object)
                + id: 1 (number)
                + name: percentage_absences_reprove (string) - `Percentual máximo de faltas que um aluno pode ter para não ser reprovado. Exemplo: Existem 200 aulas de Matématica no ano, e consideramos que percentage_absences_reprove == 15, então o aluno pode faltar no máximo 30 aulas (200*0,15).`
                + value: 20 (number)
                + `default`: 25 (number)

            + (object)
                + id: 2 (number)
                + name: grade_threshold_great (string) - `Se o aluno tiver média igual ou acima dessa nota, ele é considerado ótimo`
                + value: 9 (number)
                + `default`: 9 (number)

            + (object)
                + id: 3 (number)
                + name: grade_threshold_good (string) - `Se o aluno tiver média igual ou acima dessa nota, e menor do que "grade_threshold_great", ele é considerado bom.`
                + value:  6 (number)
                + `default`: 6 (number)

            + (object)
                + id: 4 (number)
                + name: passing_grade_threshold (string) - `Média mínima para o aluno ser aprovado em uma disciplina`
                + value: 6 (number)
                + `default`: 6 (number)
            + (object)]
                + id: 5 (number)
                + name: lesson_plan_model_id (number) - `ID do modelo de plano de aula padrão da conta`
                + `default`: 1 (number) 

## Coleção de disciplinas [/subjects]

`Subjects` São quais quer disciplinas ministradas nas escolas. ex: Português, matemática, direito constitucional entre outras.

### Criar disciplina [POST]

+ Request  (application/json)
    + Headers

            authorization: <!-- include(Token.md) -->

    + Attributes (SubjectFillable)

+ Response 201 (application/json)

    + Attributes
        + Subject (Subject)

### Listar disciplinas [GET]

<!-- include(LinkParametrosPadroesListagem.md) -->


+ Parameters
    + _q (string, optional) - Pesquisa por palavra-chave, a correspondência e incluida conjunto de resultados.
        + Members
            +name
    + _sort (string, optional) - Ordena a coluna desejada, de forma acendente ou descendente.

+ Request  (application/json)
    + Headers

            authorization: <!-- include(Token.md) -->

+ Response 200 (application/json)

    + Attributes
        + Include Paginator
        + data (array)
            + (Subject)

## Disciplina [/subjects/{subject_id}]

### Detalhes da disciplina [GET]

+ Parameters
    + subject_id: 1 (number) - ID of the Subject

+ Request  (application/json)
    + Headers

            authorization: <!-- include(Token.md) -->

+ Response 200 (application/json)

    + Attributes
        + Subject (Subject)

### Alterar disciplina [PUT]

+ Parameters
    + subject_id: 1 (number) - ID of the Subject

+ Request  (application/json)

    + Headers

            authorization: <!-- include(Token.md) -->

    + Attributes (SubjectFillable)

+ Response 200 (application/json)

    + Attributes
        + Subject (Subject)

### Excluir disciplina [DELETE]

+ Parameters
    + subject_id: 2 (number) - ID of the Subject

+ Request  (application/json)
    + Headers

            authorization: <!-- include(Token.md) -->


+ Response 204
