# Group Controles de acesso

## Solicitação de acesso [/auth/request-access]

`Request access` são solicitações de acesso que um usuário faz a uma conta.

Exemplo: considerando que a Escola Luz do Saber tem uma conta na sua aplicação, e o Professor Medeiros
vai começar a utilizar o aplicativo para registrar presenças e notas dos alunos. Então o
Professor Medeiros acessa seu aplicativo informando usuário e senha para se cadastrar.
Com isso o cadastro do Professor Medeiros fica pendente até que um usuário da Escola Luz do Saber com permissão para liberação confirme seu cadastro.

### Criar uma solicitação de acesso [POST]

+ Request  (application/json)
    + Headers

            authorization: <!-- include(Token.md) -->


+ Response 200 (application/json)

    + Attributes
        + request_access (object)
            + id: 1 (number) - Identificador único da solicitação
            + user_id: auth0|57c0840deae095471aba4093 (string) - id do usuário no microservice de autentificação auth0.
            + status: 0 (number) - Situação da solicitação.
                                0 pendente
                                1 negada
                                2 aprovada
            + created_at: `2016-08-15 20:26:39` (string) Data que a solicitação foi criada
            + updated_at: `2016-08-15 21:26:39` (string) Data da ultima alteração da solicitação


## Usuarios [/auth/user]

`Users` contem ações que identificam e gerenciam informações do usuário nesta API. 

### Detalhes do usuário logado [GET]

+ Parameters
    + user_id: 1 (number) - ID do usuário no serviço de autentificação
    + _with (string, optional) - Obtem informações do recurso relacionado.
        + Members
            + teacher
            + student

+ Request  (application/json)
    + Headers

            authorization: <!-- include(Token.md) -->

+ Response 200 (application/json)

    + Attributes
        + person (Person)
        + student (Student)
        + teacher (Teacher)

