# Data structure

## SubjectAnnualReport (object)

+ Include (Subject)
+ average_calculation: `((9.6 + 9.3)*0.4 + (9.3 + 9.8)*0.6)/2` (string) - `Calculo de média da disciplina`
+ average_formula: `( ({1º Bimestre} + {2º Bimestre})*0.4 + ({3º Bimestre} + {4º Bimestre})*0.6 )/2` (string)  - `Formula utilizada para calcular a média anual da disciplina`
+ average_year: 8.2 (number) - `Média do aluno para disciplina no ano letivo`
+ absences: 10 (number) - `Total de faltas do aluno para disciplina no ano letivo`
+ school_calendar_phases (array[object])
  + Include (SchoolCalendarPhase)
  + average: 7.2 (number) - `Média do aluno no para disciplina na fase do ano`
  + average_calculation: `(6.5 + 5.7)/2` (string) - `Calculo da média da disciplina na fase do ano` 
  + average_formula: `({Nota 1.1} + {Nota 1.2})/2` (string) - `Formula utilizada para  calcular a média da disciplina na fase do ano`    
  + absences: 2 (number) - `Total de faltas do aluno para disciplina na fase do ano`
  + student_grades (array[object])
    + Include (StudentGrade)
+ created_by: auth0|57c0840deae095471aba4093  (string) - Token do usuario logado no sistema.


## SubjectFillable (object)

+ name: Matématica  (string) - Nome da disciplina. Ex.: Matématica, Português, Fisica.

## Subject (object)

+ id: 1 (number) - Identificador único da disciplina.
+ Include (SubjectFillable)
+ created_by: auth0|57c0840deae095471aba4093  (string) - Token do usuario logado no sistema.

## StudentGradeFillable (object)

+ grade: 7.5 (number) - Nota do aluno na avaliação.
+ student_id: 1 (number) - ID do aluno.
+ subject_id: 1 (number) - ID da disciplina relacionada a turma a qual o aluno realizou a avaliação.
+ assessment_id: 1 (number) - ID da avaliação.
+ school_class_id: 1 (number) - ID da turma onde a prova foi aplicada.

## StudentGrade (object)

+ id: 1 (number) - Identificador único da nota do aluno.
+ Include (StudentGradeFillable)
+ created_by: auth0|57c0840deae095471aba4093  (string) - Token do usuario logado no sistema.

## OccurenceFillable (object)

+ comment: fulano fez isso (string) - descrição sobre os fatos da occorencia
+ level_id: 1 (number) - Nivel da occorencia
+ about_person_id: 2 (number) - ID do usuario que esta recebendo a occorencia

## Occurence (object)

+ id: 1 (number) - Identificador único da ocorrência.
+ Include (OccurenceFillable)
+ created_by: auth0|57c0840deae095471aba4093  (string) - Token do usuario logado no sistema.

## Level (object)

+ id: 1 (number)
+ name: Grave (string)
+ created_by: auth0|57c0840deae095471aba4093  (string) - Token do usuario logado no sistema.

## Assessment (object)

+ id: 1 (number) - Identificador único da avaliação
+ name: Nota N1 - Descrição da avaliação
+ school_calendar_phase_id: 1 (number) - ID da fase que a avaliação será registrada.
+ created_by: auth0|57c0840deae095471aba4093  (string) - Token do usuario logado no sistema.

## SchoolCalendarPhase (object)

+ id: 1 (number) - Identificador único da fase avaliativa do ano.
+ name: `1º Bimestre` (string)
+ start: `2016-02-01` (string) - Data inicial do período avaliativo
+ end: `2016-04-01` (string) - Ultimo dia do período avaliativo
+ school_calendar_id: 1 - ID do ano letivo a qual esta fase está relacionada.
+ created_by: auth0|57c0840deae095471aba4093  (string) - Token do usuario logado no sistema.

## SchoolCalendar (object)

+ id: 1 (number) - Identificador único do ano letivo.
+ Include (SchoolCalendarFillable)
+ created_by: auth0|57c0840deae095471aba4093  (string) - Token do usuario logado no sistema.

## SchoolCalendarFillable (object)

+ year: 2014 (number) - Ano de referência
+ start: `2016-02-01` - Inicio do ano letivo
+ end: `2016-12-10` - Fim do ano letivo
+ average_formula: `( ({1º Bimestre} + {2º Bimestre})*0.4 + ({3º Bimestre} + {4º Bimestre})*0.6 )/2` - `Fórmula utilizada para calcular médias do aluno no ano` 

## SchoolFillable (object)

+ name: Escola luz do saber (string) - Nome da escola.
+ contacts: `[
        {
          "name": "Central de atendimento ao aluno",
          "email": "ybittencourt@faria.net",
          "phone": "(13) 3237-7629"
        },
        {
          "name": "Diretoria",
          "email": "romero.adriana@terra.com.br",
          "phone": "(41) 7319-6566"
        }
      ]` (string) - Json com informações de contatos da escola.

## School (object)

+ id: 1 (number) - Identificador único da escola
+ Include (SchoolFillable)
+ created_by: auth0|57c0840deae095471aba4093  (string) - Token do usuario logado no sistema.

## SchoolClassFillable (object)

+ identifier: A (string) - Abreviação/identificação da turma. Exmplo: B, para segunda turma do 1º ano (de 1 Ano B).
+ grade_id: 1 (number) - ID do ano estudantíl.
+ shift_id: 1 (number) - ID do turno.
+ school_calendar_id: 1 (number) - ID do Ano letivo em que a turma existe.
+ school_id: 1 (number) - ID da escola relacionada.

## SchoolClass (object)

+ id: 1 (number) - Identificador único da turma.
+ Include (SchoolClassFillable)
+ created_by: auth0|57c0840deae095471aba4093  (string) - Token do usuario logado no sistema.

## SchoolClassSubject (object)

+ id: 1 (number) - Identificador único da disciplina em uma turma.
+ school_class_id - ID da turma
+ subject_id - ID da disciplina
+ created_by: auth0|57c0840deae095471aba4093  (string) - Token do usuario logado no sistema.

## Shift (object)

+ id: 1 (number) - Identificador único do turno.
+ name: Matutino (string) - Nome do turno. Exemplo: Vespertino, matutino, noturno.
+ created_by: auth0|57c0840deae095471aba4093  (string) - Token do usuario logado no sistema.

## LessonFillable (object)

+ school_class_id: 1 (number) - `Identificador único da turma.`
+ subject_id: 1 (number) - `Identificador único da disciplina (Matématica, física, ...).`
+ start: `2016-08-30 13:17:11` (string) - `Data e horário de inicio da aula.`
+ end: `2016-08-30 13:17:11` (string) - `Data e horário de termino da aula.`
+ teacher_id: 1 (number) - `ID do professor.`

## Lesson (object)

+ id: 1 (number) - `Identificador único  da aula.`
+ Include (LessonFillable)
+ created_by: auth0|57c0840deae095471aba4093  (string) - Token do usuario logado no sistema.

## Teacher (object)

+ id: 1 (number) - `Identificador único do professor.`
+ person_id: 1 (number) - `ID das informações básicas de pessoa do professor (nome, sobrenome, etc.)`
+ created_by: auth0|57c0840deae095471aba4093  (string) - Token do usuario logado no sistema.

## Person (object)

+ id: 1 (number) - Identificador único da pessoa
+ name: Caio Fernando Chaves (string) - Nome
+ age: 15 (number) - Idade
+ birthday: `2001-04-21` (string) - Data de aniversário
+ piture: `https://randomuser.me/api/portraits/lego/6.jpg` (string) - Foto
+ gender: male (string)
+ place_of_birth: Santa Alenssandra (string) - Cidade de nascimento
+ more: descricao (string) - Mais detalhes sobre a pessoa
+ phone: `(62) 8385-5421` (string) - numero de telefone da pessoa
+ created_by: auth0|57c0840deae095471aba4093  (string) - Token do usuario logado no sistema.

## Student (object)

+ id: 1 (number) - Identificador único do estudante.
+ person_id: 1 (number) - ID das informações básicas de pessoa do aluno (nome, sobrenome, etc.).
+ created_by: auth0|57c0840deae095471aba4093  (string) - Token do usuario logado no sistema.

## AttendanceRecordFillable (object)

+ lesson_id: 1 (number) - Identificador único da aula relacionada
+ student_id: 1 (number) - Identificador único do aluno
+ presence: 1 (number) - `0=Faltou a aula.1=Presente.2=Falta abonada.

## AttendanceRecord (object)

+ id: 1 (number) - Identificador único do registro de presença
+ Include (AttendanceRecordFillable)
+ created_by: auth0|57c0840deae095471aba4093  (string) - Token do usuario logado no sistema.

## Paginator (object)

+ total: 25 (number) - Total de resultados encontrados
+ per_page: 15 (number) - Quantidade de resultados por página
+ current_page: 1 (number) - Página atual
+ last_page: 2 (number) - Ultima página
+ next_page_url: `http://localhost/api/<resource>?page=2` (string, nullable) - Url para resultados da proxima página
+ prev_page_url: null (string, nullable) - Url para resultados da página anterior
+ from: 1 (number) - Número inicial de resultados de paginação da página atual
+ to: 15 (number) - Número final de resultados de paginação da página atual
