# Group Escolas e turmas

'Escolas' (definido como School nesta API) são quaisquer entidades educacional associadas a uma conta.
        Exemplo: escola, CMDEIS (Centros Municipais de Educação Infantil), universidades.
'Turmas' (definido como SchoolClass) são as turmas de uma escola que existem em um determinado ano calendário escolar (definido como SchoolCalendar).

## Coleção de escolas [/schools]

### Listar escolas [GET]
<!-- include(LinkParametrosPadroesListagem.md) -->

+ Parameters
    + _q (string, optional) - Pesquisa por palavra-chave, a correspondência e incluida conjunto de resultados.
        + Members
            +name
    + _sort (string, optional) - Ordena a coluna desejada, de forma acendente ou descendente.
    + _with (string, optional) - Obtem informações do recurso relacionado.
        + Members
            + schoolClasses

+ Request  (application/json)
    + Headers

            authorization: <!-- include(Token.md) -->

+ Response 200 (application/json)

    + Attributes
        + Include (Paginator)
        + data (array)
            + (School)

### Criar escola [POST]

+ Request  (application/json)
    + Headers

            authorization: <!-- include(Token.md) -->

    + Attributes (SchoolFillable)

+ Response 201 (application/json)

    + Attributes
        + School (School)

## Escola [/schools/{school_id}]

### Detalhes da escola [GET]

+ Parameters
    + school_id: 1 (number) - Identificador único da escola
    + _with (string, optional) - Obtem informações do recurso relacionado.
        + Members
            + schoolClasses

+ Request  (application/json)
    + Headers

            authorization: <!-- include(Token.md) -->

+ Response 200 (application/json)

    + Attributes
        + school (School)


### Alterar escola [PUT]

+ Parameters
    + school_id: 1 (number) - Identificador único da escola

+ Request  (application/json)

    + Headers

            authorization: <!-- include(Token.md) -->

    + Attributes (SchoolFillable)

+ Response 200 (application/json)

    + Attributes
        + School (School)

### Excluir escola [DELETE]

+ Parameters
    + school_id: 1 (number) - Identificador único da escola

+ Request  (application/json)

    + Headers

            authorization: <!-- include(Token.md) -->

+ Response 204

## Coleção de turmas [/school-classes]

### Listar turmas [GET]

<!-- include(LinkParametrosPadroesListagem.md) -->

+ Parameters
    + _q (string, optional) - Pesquisa por palavra-chave, a correspondência e incluida conjunto de resultados.
        + Members
            +identifier
    + _sort (string, optional) - Ordena a coluna desejada, de forma acendente ou descendente.
    + _with (string, optional) - Obtem informações do recurso relacionado.
        + Members
            + shift - Turno.
            + students - Aluno.
            + schoolCalendar - Ano letivo.
            + subjects - Avaliação.
            + progressSheet - Ficha descritiva que é utilizada para avaliar os alunos da turma. 

+ Request  (application/json)

    + Headers

            authorization: <!-- include(Token.md) -->

+ Response 200 (application/json)

    + Attributes
        + Include Paginator
        + data (array)
            + (SchoolClass)

### Criar turma [POST]

+ Request  (application/json)
    + Headers

            authorization: <!-- include(Token.md) -->

    + Attributes (SchoolClassFillable)

+ Response 201 (application/json)

    + Attributes
        + school_class (SchoolClass)

## Turma [/school-classes/{school_class_id}]

+ Parameters
    - school_class_id: 1 (number) - ID of the school class

### Detalhes da turma [GET]

+ Parameters
    + _with (string, optional) - Obtem informações do recurso relacionado.
        + Members
            + shift - Turno.
            + students - Alunos.
            + schoolCalendar - Calendário letivo/ano letivo em qual a turma foi criada.
            + subjects - Disciplinas ministradas na turma.
            + progressSheet - Filha de avaliação descritiva da turma.
            + progressSheet.items - Filha de avaliação descritiva com items.

+ Request  (application/json)
    + Headers

            authorization: <!-- include(Token.md) -->

+ Response 200 (application/json)

    + Attributes
        + school_class (SchoolClass)

### Alterar turma [PUT]

+ Parameters
    + school_class_id: 1 (number) - ID of the School

+ Request  (application/json)
    + Headers

            authorization: <!-- include(Token.md) -->

    + Attributes (SchoolClassFillable)

+ Response 200 (application/json)

    + Attributes
        + school_class (SchoolClass)

### Excluir turma [DELETE]

+ Parameters
    + school_class_id: 1 (number) - ID of the School

+ Request  (application/json)

    + Headers

            authorization: <!-- include(Token.md) -->

+ Response 204

## Relatório anual da turma por disciplina [/school-classes/{school_class_id}/annual-report-by/{subject_id}{?_sort_students}]

### Relatório anual por disciplina [GET]

+ Parameters 
    + _sort_students (string, optional) - Para ordenar os resultados de report_by_user
        + Members
            + name  - Para listar estudantes ordenado por nome em ordem crescente
            + `-name` - Para listar em ordem decrescente

+ Request  (application/json)
    + Headers

            authorization: <!-- include(Token.md) -->

+ Response 200 (application/json)

    + Attributes

        + report_by_student (array)
            + (object)
                + student (object)
                    + id: 1 (number) - ID do estudante
                    + person (Person) - Informações básicas do estudante
                + school_calendar_report (object) - Relatório do aluno durante o calendário escolar para disciplina (subject_id)
                    + average: 9.2 (number) - Média do aluno no ano
                    + average_calculation: `((4.6 + 1.2)*0.4 + (9 + 3.1)*0.6)/2` (string) - Formula da média do aluno no ano
                    + average_formula: `(({1º Bimestre}+...+ {4º Bimestre})*0.6)/2"` (string) - Calculo da média do aluno no ano
                    + absences: 22 (number) - Total de faltas do aluno na disciplina em todo o calendário escolar
                + phases_report (object)  - Relatório do aluno durante as fases do calendário escolar
                    + school_calendar_phase_id: 1 (number) - ID da fase do calendário escolar
                    + average: 7.9 (number) - Média do aluno na fase para a disciplina
                    + average_calculation: `({8.3} + {7.4})/2` (string) - Calculo da média
                    + average_formula: `({Nota 1} + {Nota 2})/2` (string) - Formula utilizada no calculo
                    + absences: 4 (number) - Total de faltas na fase
                    + student_grades (array) - Notas do aluno que compõem a média da fase
                        + (object)
                            + id: 1 (number) - ID do registro de nota do aluno na avaliação
                            + grade: 8.3 (number) - Nota do aluno na avaliação (assessment_id)
                            + assessment_id: 1 (number) - ID da avaliação da fase
                        + (object)
                            + id: 2 (number)
                            + grade: 7.4 (number)
                            + assessment_id: 2 (number)
        + school_class_report (array)
            + (object)
                + school_calendar_report (object) - Relatório da turma no calendário escolar para uma disciplina.
                    + average: 8.2 (number) - Media aritimetica das notas dos alunos da turma no calendário escolar de uma disciplina.
                + phases_report (array)  - Relatório da tuma em uma fase do calendário escolar para uma disciplina.
                    + (object)
                        + school_calendar_phase_id: 1 (number) - ID da fase do calendário escolar para uma disciplina.
                        + average: 7.7 (number) - Media aritimetica das notas de todos os alunos da turma em uma disciplina para a fase do calendário escolar.


## Faltas dos alunos da turma [/school-classes/{school_class_id}/absences]

Esse recurso representa todas as faltas dos alunos em aulas da turma.

### Faltas dos alunos [GET]

+ Parameters 
    + school_class_id (numeric) - ID  da turma


+ Request  (application/json)
    + Headers

            authorization: <!-- include(Token.md) -->

+ Response 200 (application/json)

    + Attributes

        + (array[object])
            + student_id: 1 (number) - ID do estudante
            + school_calendar_phases (object) - Phases do calendário escolar relacionado a turma
                + school_calendar_phase_id: 1 (number) - ID da fase do calendário escolar
                + absences: 4 (number) - Total de faltas do aluno na fase