<!-- include(DefinitionOfApi.md) -->

<!-- include(Authentication.md) -->

<!-- include(Account.md) -->

<!-- include(Schools.md) -->

<!-- include(People.md) -->

<!-- include(Students.md) -->

<!-- include(Lessons.md) -->

<!-- include(AttendanceRecords.md) -->

<!-- include(Assessments.md) -->

<!-- include(Occurrence.md) -->

<!-- include(StudentGrades.md) -->

<!-- include(DataStructure.md) -->