<!-- include(DefinitionOfApi.md) -->

<!-- include(Authentication.md) -->

<!-- include(Parametros.md) -->

<!-- include(Account.md) -->

<!-- include(Schools.md) -->

<!-- include(People.md) -->

<!-- include(Students.md) -->

<!-- include(Lessons.md) -->

<!-- include(AttendanceRecords.md) -->

<!-- include(Assessments.md) -->

<!-- include(Occurrences.md) -->

<!-- include(StudentGrades.md) -->

<!-- include(Subjects.md) -->

<!-- include(DataStructure.md) -->
